# Generated by Django 3.1.2 on 2020-10-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
    ]
