# Generated by Django 3.1.2 on 2020-10-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='olist.Category'),
        ),
    ]
