# Generated by Django 3.1.2 on 2020-10-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olist', '0004_auto_20201028_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='files/')),
            ],
        ),
    ]
